### PR TITLE
Diary Web App User Interface

### PR DESCRIPTION
**Pull request by charisschomba**
This Repository contains Designs for a Dairy web app with five pages.
1.index.html which is the home page.
-This page allows users to View all entries in their dairy.
-A profile section where a user can enable or disable remainder settings.
2.singup.html,this is the page where new users register's before they can log in.
3.singin.html,after successfully registering,users can now log into their accounts.
4.detail.html,this page allow users to view contents of their single entry.
5.entry.html which enables logged in users add an entry to their personal diary.
--img folder that holds all the images used.
--css folder that contains the styling for the page
screenshot from 2018-07-12 21-12-50
screenshot from 2018-07-12 21-13-36
screenshot from 2018-07-12 21-13-52
screenshot from 2018-07-12 21-14-04
screenshot from 2018-07-12 21-14-18

### CODE REVIEW

**Comment by YAHYA-H** [comment]
GREAT WORK :100:

**Comment by SrMoffat** [comment]
Good job bro. I think you have capture the project requirements very well.

**Comment by imireallan** [comment]
nice work..av checked the templates and are working fine

**Comment by Kelvintrc** [comment]
nice template

**Pull request merged**
